server:
  port: 8000
spring:
  application:
    name: enol-order-service
  cloud:
    nacos:
      discovery:
        server-addr: http://192.168.0.194:8848
    sentinel:
      transport:
        #sentinel控制台路径
        dashboard: http://192.168.0.194:8080
        #sentinel服务端口
        port: 9998
  zipkin:
    base-url: http://192.168.0.194:9411/ #zipkin地址
    discovery-client-enabled: false #不⽤开启服发现
  sleuth:
    sampler:
      probability: 1.0 #采样百分⽐

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cloud_order?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
# 控制台输出sql、下划线转驼峰
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

#配置随机负载均衡策略
enol-video-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

#开启feign对sentinel的支持
feign:
  sentinel:
    enabled: true
